version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=task_manager.settings

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pasha
      POSTGRES_USER: lovedr6s
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"