# Generated by Django 5.2 on 2025-05-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='executor',
        ),
    ]
