# Generated by Django 5.2 on 2025-05-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_creator_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='assignee',
        ),
    ]
